/*
 * replicate_server.c - Server implementation for distributed computing platform
 * Note: This file contains only the service functions.
 * The main() function is in replicate_svc.c (generated by rpcgen)
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <time.h>
#include <rpc/rpc.h>
#include <errno.h>
#include "replicate.h"

#define OUTPUT_DIR "replicate_out"
#define MAX_CMD_LEN 1024

typedef struct
{
    pid_t child_pid;
    int job_id;
    int active;
} JobProcess;

JobProcess current_job = {0, -1, 0};
int server_active = 1;

/* Signal handler for SIGCHLD */
void sigchld_handler(int sig)
{
    int status;
    pid_t pid = waitpid(-1, &status, WNOHANG);
    if (pid > 0 && pid == current_job.child_pid)
    {
        current_job.active = 0;
        current_job.child_pid = 0;
        current_job.job_id = -1;
        printf("Child process %d terminated\n", pid);
    }
}

/* Signal handler for SIGTERM (stop server) */
void sigterm_handler(int sig)
{
    if (current_job.active && current_job.child_pid > 0)
    {
        printf("Terminating current job %d (PID: %d)\n", 
               current_job.job_id, current_job.child_pid);
        kill(current_job.child_pid, SIGKILL);
        current_job.active = 0;
        current_job.child_pid = 0;
        current_job.job_id = -1;
    }
}

/* Get CPU load from /proc/loadavg */
float get_cpu_load(void)
{
    FILE *fp = fopen("/proc/loadavg", "r");
    if (!fp)
        return 0.0;

    float load;
    if (fscanf(fp, "%f", &load) != 1) {
        load = 0.0;
    }
    fclose(fp);
    return load;
}

/* Execute hyper_link command */
int *hyper_link_1_svc(struct hyper_link_args *argp, struct svc_req *rqstp)
{
    static int result;

    printf("Received hyper_link request for job %d\n", argp->job_num);
    
    if (!server_active)
    {
        printf("Server is inactive, rejecting job %d\n", argp->job_num);
        result = -1;
        return &result;
    }

    /* Parse arguments */
    int job_num = argp->job_num;
    int a1 = argp->a1;
    int a2 = argp->a2;
    int a3 = argp->a3;
    int a4 = argp->a4;
    int a5 = argp->a5;
    int a6 = argp->a6;

    /* Fork child process to execute hyper_link */
    pid_t pid = fork();

    if (pid == 0)
    {
        /* Child process */
        char cmd[MAX_CMD_LEN];
        char output_file[MAX_CMD_LEN];

        /* Create output filename */
        snprintf(output_file, sizeof(output_file), "%s/hyper_link_%d.out",
                 OUTPUT_DIR, job_num);

        /* Redirect stdout to file */
        int fd = open(output_file, O_WRONLY | O_CREAT | O_TRUNC, 0644);
        if (fd < 0)
        {
            perror("Failed to open output file");
            exit(1);
        }
        dup2(fd, STDOUT_FILENO);
        dup2(fd, STDERR_FILENO);
        close(fd);

        /* Execute hyper_link */
        snprintf(cmd, sizeof(cmd), "./hyper_link %d %d %d %d %d %d %d",
                 job_num, a1, a2, a3, a4, a5, a6);

        printf("Executing: %s\n", cmd);
        execl("/bin/sh", "sh", "-c", cmd, NULL);
        
        /* If we get here, execl failed */
        perror("Failed to execute hyper_link");
        exit(1);
    }
    else if (pid > 0)
    {
        /* Parent process */
        current_job.child_pid = pid;
        current_job.job_id = job_num;
        current_job.active = 1;
        result = 0;
        printf("Started job %d with PID %d\n", job_num, pid);
    }
    else
    {
        perror("Fork failed");
        result = -1;
    }

    return &result;
}

/* Square function */
int *square_1_svc(struct square_args *argp, struct svc_req *rqstp)
{
    static int result;
    result = (argp->value) * (argp->value);
    printf("Square of %d = %d\n", argp->value, result);
    return &result;
}

/* Get CPU load */
float *get_load_1_svc(struct load_args *argp, struct svc_req *rqstp)
{
    static float result;
    result = get_cpu_load();
    printf("CPU load requested: %.2f\n", result);
    return &result;
}

/* Get server status */
int *get_status_1_svc(struct status_args *argp, struct svc_req *rqstp)
{
    static int result;
    result = server_active ? 1 : 0;
    printf("Status requested: %s\n", server_active ? "ACTIVE" : "INACTIVE");
    return &result;
}

/* Stop server */
int *stop_server_1_svc(struct stop_args *argp, struct svc_req *rqstp)
{
    static int result;

    printf("Stop server command received\n");
    server_active = 0;

    /* Kill current job if any */
    if (current_job.active && current_job.child_pid > 0)
    {
        printf("Killing current job %d (PID: %d)\n", 
               current_job.job_id, current_job.child_pid);
        kill(current_job.child_pid, SIGKILL);
        current_job.active = 0;
        current_job.child_pid = 0;
        current_job.job_id = -1;
    }

    result = 0;
    return &result;
}

/* Start server */
int *start_server_1_svc(struct start_args *argp, struct svc_req *rqstp)
{
    static int result;
    printf("Start server command received\n");
    server_active = 1;
    result = 0;
    return &result;
}

/* Execute custom command - FIXED: Return type is char **, but we need to return a pointer to a string */
char **execute_command_1_svc(struct command_args *argp, struct svc_req *rqstp)
{
    /* Static array to hold the result string */
    static char *result;  /* This will point to our static buffer */
    static char buffer[MAX_CMD_LEN];  /* Static buffer to hold the actual string */
    
    printf("Executing command: %s\n", argp->cmd);

    FILE *fp = popen(argp->cmd, "r");
    if (!fp)
    {
        strcpy(buffer, "Command execution failed");
        result = buffer;
        return &result;  /* Return pointer to the string pointer */
    }

    size_t len = fread(buffer, 1, sizeof(buffer) - 1, fp);
    buffer[len] = '\0';
    pclose(fp);
    
    printf("Command result: %s\n", buffer);
    
    /* Set result to point to our buffer */
    result = buffer;
    
    /* Return pointer to result (which is a pointer to our string) */
    return &result;
}
