/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REPLICATE_H_RPCGEN
#define _REPLICATE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct hyper_link_args {
	int job_num;
	int a1;
	int a2;
	int a3;
	int a4;
	int a5;
	int a6;
	int a7;
	int a8;
};
typedef struct hyper_link_args hyper_link_args;

struct square_args {
	int value;
};
typedef struct square_args square_args;

struct load_args {
	int dummy;
};
typedef struct load_args load_args;

struct status_args {
	int dummy;
};
typedef struct status_args status_args;

struct stop_args {
	int dummy;
};
typedef struct stop_args stop_args;

struct start_args {
	int dummy;
};
typedef struct start_args start_args;

struct command_args {
	char *cmd;
};
typedef struct command_args command_args;

#define REPLICATE_PROG 0x31234567
#define REPLICATE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define HYPER_LINK 1
extern  int * hyper_link_1(hyper_link_args *, CLIENT *);
extern  int * hyper_link_1_svc(hyper_link_args *, struct svc_req *);
#define SQUARE 2
extern  int * square_1(square_args *, CLIENT *);
extern  int * square_1_svc(square_args *, struct svc_req *);
#define GET_LOAD 3
extern  float * get_load_1(load_args *, CLIENT *);
extern  float * get_load_1_svc(load_args *, struct svc_req *);
#define GET_STATUS 4
extern  int * get_status_1(status_args *, CLIENT *);
extern  int * get_status_1_svc(status_args *, struct svc_req *);
#define STOP_SERVER 5
extern  int * stop_server_1(stop_args *, CLIENT *);
extern  int * stop_server_1_svc(stop_args *, struct svc_req *);
#define START_SERVER 6
extern  int * start_server_1(start_args *, CLIENT *);
extern  int * start_server_1_svc(start_args *, struct svc_req *);
#define EXECUTE_COMMAND 7
extern  char ** execute_command_1(command_args *, CLIENT *);
extern  char ** execute_command_1_svc(command_args *, struct svc_req *);
extern int replicate_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define HYPER_LINK 1
extern  int * hyper_link_1();
extern  int * hyper_link_1_svc();
#define SQUARE 2
extern  int * square_1();
extern  int * square_1_svc();
#define GET_LOAD 3
extern  float * get_load_1();
extern  float * get_load_1_svc();
#define GET_STATUS 4
extern  int * get_status_1();
extern  int * get_status_1_svc();
#define STOP_SERVER 5
extern  int * stop_server_1();
extern  int * stop_server_1_svc();
#define START_SERVER 6
extern  int * start_server_1();
extern  int * start_server_1_svc();
#define EXECUTE_COMMAND 7
extern  char ** execute_command_1();
extern  char ** execute_command_1_svc();
extern int replicate_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_hyper_link_args (XDR *, hyper_link_args*);
extern  bool_t xdr_square_args (XDR *, square_args*);
extern  bool_t xdr_load_args (XDR *, load_args*);
extern  bool_t xdr_status_args (XDR *, status_args*);
extern  bool_t xdr_stop_args (XDR *, stop_args*);
extern  bool_t xdr_start_args (XDR *, start_args*);
extern  bool_t xdr_command_args (XDR *, command_args*);

#else /* K&R C */
extern bool_t xdr_hyper_link_args ();
extern bool_t xdr_square_args ();
extern bool_t xdr_load_args ();
extern bool_t xdr_status_args ();
extern bool_t xdr_stop_args ();
extern bool_t xdr_start_args ();
extern bool_t xdr_command_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REPLICATE_H_RPCGEN */
